[project]
name = "wizit_context_ingestor"
version = "0.3.0-beta-8"
description = "Contextual Rag with Cloud Solutions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic[vertex]>=0.66.0",
    "boto3>=1.40.23",
    "langchain-aws>=0.2.31",
    "langchain-chroma>=0.2.6",
    "langchain-experimental>=0.3.4",
    "langchain-google-vertexai>=2.0.28",
    "langchain-redis>=0.2.3",
    "langgraph>=0.6.8",
    "pillow>=11.3.0",
    "pymupdf>=1.26.4",
]

[dependency-groups]
dev = [
    "memray>=1.18.0",
    "pyinstrument>=5.1.1",
    "python-dotenv>=1.1.1",
]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
