[project]
name = "ckan-pilot"
version = "1.1.1"
description = "Manage CKAN project development, operations and maintenance with a state-of-the-art command-line interface (CLI) and modern toolset."
authors = [
    {name = "Keitaro Inc",email = "info@keitaro.com"}
]
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "auto-click-auto>=0.1.5",
    "click>=8.1.8",
    "click-log>=0.4.0",
    "copier>=9.6.0",
    "docker>=7.1.0",
    "pyfiglet>=1.0.2",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "rich>=13.9.4",
]

[project.urls]
Homepage = "https://github.com/keitaroinc/ckan-pilot"
Issues = "https://github.com/keitaroinc/ckan-pilot/issues"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "ruff>=0.9.10,<0.11.0",
    "coverage>=7.6.12",
    "pytest>=8.3.5",
    "yamllint>=1.35.1",
]

[project.scripts]
ckan-pilot = "ckan_pilot.root:cli"

[tool.ruff]
line-length = 120
exclude = [
    "ckan_pilot/templates/docker.py",

]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "N",  # PEP8 naming convetions
    "PL", # pylint
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
branch = true
include = ["ckan_pilot/*"]
command_line = "-m pytest"
relative_files = true
