[tool.poetry]
name = "treeplots"
version = "0.10.7"
description = "CLI tool to create tree views from a csv file with child-parent relationships."
authors = ["cheny"]
readme = "README.md"
packages = [{include = "plot_tree"}]

[tool.poetry.dependencies]
python = "^3.9.2"
pyyaml = "~6.0.1"
anytree = "~2.13.0"
typer = ">=0.19.2, <1.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
plot = "plot_tree.tree_plotter:main"
treeplots = "plot_tree.cli:app"
