[project]
name = "pro-craft"
version = "0.1.27"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ "aiomysql>=0.2.0", "anyio>=4.11.0", "db-help>=0.2.2", "fastapi>=0.119.0", "llmada>=1.1.11", "pyyaml>=6.0.3", "toml>=0.10.2", "utils-tool==0.1.3", "uvicorn>=0.38.0",]

[tool.setuptools.package-data]
pro_craft = [ "config.yaml",]

[tool.pytest.ini_options]
testpaths = [ "tests",]
pythonpath = [ "src",]
