[project]
name = "digital-life"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ "anyio>=4.11.0", "fastapi>=0.119.1", "llama-index==0.12.30", "llama-index-vector-stores-qdrant==0.6.1", "pro-craft>=0.1.25", "qdrant-client>=1.15.1", "redis>=7.0.0", "utils-tool==0.1.3", "uvicorn>=0.38.0", "volcengine-python-sdk==4.0.6",]

[tool.setuptools.package-data]
digital_life = [ "config.yaml",]

[tool.pytest.ini_options]
testpaths = [ "tests",]
pythonpath = [ "src",]
