[project]
name = "akari-bot-webui"
version = "0.3.2"
description = ""
authors = [
    {name = "OasisAkari",email = "oasisakari@gmail.com"},
    {name = "DoroWolf",email = "dorowolf314@gmail.com"},
    {name = "_LittleC_",email = "i@ltlec.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
package-mode = true
packages = [
    { include = "akari_bot_webui" },
]
include = ["akari_bot_webui/dist"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
