[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "airobo"
version = "0.1.67"
description = "A CLI tool for Airobo tasks"
authors = [
    { name="Joshua Morvant", email="joshua@aiarobo.com" }
]
readme = "README.md"
requires-python = ">=3.7"
dependencies = []

[project.scripts]
airobo = "airobo.cli:main"
