[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maleo-types"
version = "0.0.22"
description = "Types package for MaleoSuite"
authors = [
    { name = "Agra Bima Yuda", email = "agra@nexmedis.com" }
]
license = { text = "Proprietary" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "cfgv>=3.4.0",
    "click>=8.2.1",
    "distlib>=0.4.0",
    "filelock>=3.19.1",
    "identify>=2.6.13",
    "mypy_extensions>=1.1.0",
    "nodeenv>=1.9.1",
    "packaging>=25.0",
    "pathspec>=0.12.1",
    "platformdirs>=4.4.0",
    "pre_commit>=4.3.0",
    "PyYAML>=6.0.2",
    "virtualenv>=20.34.0"
]

[tool.setuptools]
packages = ["maleo.types"]

[tool.setuptools.package-data]
"maleo.types" = ["*.json", "*.yaml"]

[tool.setuptools.package-dir]
"maleo.types" = "src"
