[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hiutils-aymen"
version = "0.1.8"
description = "Shared utilities for hierarchical interaction regression (UniLasso, Lasso, OLS, CV utilities)."
readme = { file = "README.md", content-type = "text/markdown", charset = "UTF-8" }
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [{name = "Aymen Echarghaoui"}]
keywords = ["lasso", "statistics", "interactions", "machine-learning", "scikit-learn"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
]

dependencies = [
  "numpy>=1.22",
  "scipy>=1.9",
  "scikit-learn>=1.1",
  "matplotlib>=3.5",
  "seaborn>=0.11",
  "adelie>=0.2"  
]

[tool.setuptools.packages.find]
where = ["src"]
