[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chatbot-tracer"
version = "0.8.0"

description = "A tool to model chatbots and create profiles to test them."
authors = [
    { name = "IvÃ¡n Sotillo", email = "ivan.delhorno@uam.es" }
]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["chatbot", "testing", "automation", "ai"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Testing",
]
dependencies = [
    "bs4>=0.0.2",
    "chatbot-connectors==0.6",
    "colorama>=0.4.6",
    "google-generativeai>=0.8.5",
    "graphviz>=0.20.3",
    "langchain>=0.3.27",
    "langchain-core>=0.3.60",
    "langchain-google-genai>=2.0.10",
    "langchain-openai>=0.3.17",
    "langgraph>=0.4.5",
]

[project.urls]
Homepage = "https://github.com/Chatbot-TRACER/TRACER"
Repository = "https://github.com/Chatbot-TRACER/TRACER"
Issues = "https://github.com/Chatbot-TRACER/TRACER/issues"

[project.scripts]
tracer = "tracer.main:main"
tracer-coverage-analyzer = "tracer.scripts.coverage_analyzer:main"
tracer-coverage-merger = "tracer.scripts.coverage_merger:main"
tracer-graph-generator = "tracer.scripts.graph_generator:main"
tracer-validation = "tracer.scripts.validation_script:main"

[project.optional-dependencies]
dev = [
    "ruff>=0.1.0",
]

[tool.setuptools.packages.find]
include = ["tracer*"]

[tool.ruff]
# default is too small
line-length = 120
target-version = "py311"
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.lint]
# E: pycode style (error)
# W: pycode style (warning)
# F: Pyflakes
# I: ishort
# ANN: type annotations
# D: docstrings
# B: bugbear
select = [
    "ALL"
]
ignore = [
    "E501", # line too long
    # "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", # Common missing docstring rules
    "COM812", # Creates incompatibility with formatter
    "T201", # Doesnt let you use prints
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.13",
]
