[project]
name = "strangeworks-braket-extension"
version = "0.7.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Strange Devs", email = "hello@strangeworks.com" },
]
requires-python = ">=3.10"
dependencies = [
    "amazon-braket-sdk>=1.96.0",
    "strangeworks-extensions>=0.7.0",
]

[project.entry-points.sdk-extensions]
amazon-braket = "strangeworks_braket_extension:setup"

[tool.uv.sources.strangeworks-extensions]
workspace = true

[tool.hatch.build.targets.sdist]
only-include = [
    "src/strangeworks_braket_extension",
]

[tool.hatch.build.targets.wheel]
packages = [
    "src/strangeworks_braket_extension",
]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
