[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "elektropy"
version = "0.1.0"
description = "A Python library for circuit and digital electronics solving."
readme = "README.md"
authors = [{ name = "Daniel Olsen", email = "184446@stud.hvl.no" }]
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "sympy>=1.12",
]

[project.urls]
Homepage = "https://github.com/danielols3n/elektropy"
Issues = "https://github.com/danielols3n/elektropy/issues"