[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "obsiasset"
version = "0.1.3"
description = "Obsidian Asset Manager"
readme = "README.md"
requires-python = ">=3.7"
license-files = ["LICEN[CS]E*"]
authors = [
    { name = "Will", email = "bxwill.shi@gmail.com" }
]
maintainers = [
    { name = "Will", email = "bxwill.shi@gmail.com" }
]
dependencies = [
    "PyYAML",
    "tabulate",
    "requests",
    "argcomplete",
    "jinja2",
]
keywords = ["obsidian", "vault", "asset", "cli", "manage"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X"
]

[project.urls]
Homepage = "https://github.com/bxwillshi/obsidian-asset-manager"

[project.scripts]
obsiasset = "obsiasset.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-data = { "obsiasset" = ["config/**", "tmpl/**", "schema/**", "i18n/**", "sample/**"] }
