[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "targetseeker"
version = "0.0.1"
description = "Placeholder package to reserve name."
authors = [{name="Rahul Brahma", email="rahul.brahma@uni-greifswald.de"}]
license = {text="MIT"}
readme = "README.md"
requires-python = ">=3.7"
