[build-system]
requires = ['setuptools==80.9.0']
build-backend = 'setuptools.build_meta'

[project]
authors = [
    { name='Romaan Khadeer', email='romaan@dollarmates.com' },
]
classifiers = [
    'Programming Language :: Python :: 3.10',
    'Framework :: Django',
    'Operating System :: OS Independent',
    'Environment :: Web Environment'
]
license-files = [ "LICENSE" ]
description = 'DM Core Redis'
dependencies = [
    'Django==5.2.5',
    'django-redis==6.0.0',
    'python-redis-lock==4.0.0',
    'pytz==2023.3',
    'redis==5.0.4',
    'rq==2.0.0',
    'dm-core-crypto',
]
name = 'dm-core-redis'
readme = 'README.md'
requires-python = '==3.12.*'
version = '1.0.1'

[project.urls]
Homepage = 'https://www.dollarmates.com'
Source = 'https://github.com:dollarmates/dm-libs.git'

[tool.setuptools.packages.find]
where = ['src']
