[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[project]
name = "autocamlight"
version = "0.1.0"
readme = "README.md"
description = "Automate your webcam light."
authors = [
    {name = "Dries007", email = "admin@dries007.net"},
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = [
    "ha-mqtt-discoverable>=0.22.1",
    "inotify>=0.2.12",
    "pydantic-settings>=2.11.0",
]

[project.scripts]
autocamlight = "autocamlight.__main__:main"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.14.0",
]

#  ___       __  __
# | _ \_  _ / _|/ _|
# |   / || |  _|  _|
# |_|_\\_,_|_| |_|
[tool.ruff]
line-length = 140
fix = true

[tool.ruff.lint]
# Add extra checks to default. See https://docs.astral.sh/ruff/rules/
extend-select = [
    "F",  # pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "I",  # isort
    "B",  # flake8-bugbear
    "G",  # flake8-logging
    "UP",  # pyupgrade
    "PT",  # flake8-pytest-style
    "SIM",  # flake8-simplify
    "ISC",  # flake8-implicit-str-concat
    "PIE",  # flake8-pie
    "FLY",  # flynt
    "PERF",  # perflint
    "FURB",  # refurb
    "RUF",  # ruff
]
ignore = [
    "E501",  # line-too-long, ignored because the formatter has some leeway this rule doesn't understand
]

[tool.ruff.format]
docstring-code-format = true
