import_config: default

flow:
  dashscope_deep_research:
    flow_content: dashscope_deep_research_op
    stream: true

  langchain+bailian_search:
    flow_content: langchain_deep_research_op2 << (conduct_research_op << bailian_web_search_op << think_tool_op << research_complete_op) << think_tool_op << research_complete_op
    stream: true

  langchain+bocha_search:
    flow_content: langchain_deep_research_op2 << (conduct_research_op << bailian_web_search_op << think_tool_op << research_complete_op) << think_tool_op << research_complete_op
    stream: true

  langchain+brief+bailian_search:
    flow_content: langchain_deep_research_op << (conduct_research_op << bailian_web_search_op << think_tool_op << research_complete_op) << think_tool_op << research_complete_op
    stream: true

  langchain+brief+bocha_search:
    flow_content: langchain_deep_research_op << (conduct_research_op << bocha_web_search_op << think_tool_op << research_complete_op) << think_tool_op << research_complete_op
    stream: true

  task_react:
    flow_content: task_react_op
    stream: true

op:
  langchain_deep_research_op2:
    backend: langchain_deep_research_op
    params:
      enable_research_brief: false

  tavily_search_op:
    backend: tavily_search_op
    params:
      save_answer: false
      output_schema_mapping:
        tavily_search_result: long_text

  dashscope_search_op:
    backend: dashscope_search_op
    params:
      save_answer: true

  bailian_web_search_op:
    backend: base_mcp_op
    params:
      mcp_name: tongyi_search
      tool_name: bailian_web_search
      save_answer: true
      input_schema_optional:
        - count
      input_schema_deleted:
        - ctx

  bocha_web_search_op:
    backend: base_mcp_op
    params:
      mcp_name: bochaai_search
      tool_name: bocha_web_search
      save_answer: true
      input_schema_optional:
        - freshness
        - count

  brave_web_search_op:
    backend: base_mcp_op
    params:
      mcp_name: brave_search
      tool_name: brave_web_search
      save_answer: true
      input_schema_optional:
        - offset
        - count

  bailian_web_parser_op:
    backend: base_mcp_op
    params:
      mcp_name: tongyi_web_parser
      tool_name: bailian_web_parser
      save_answer: true
      input_schema_optional:
        - format

  extract_long_text_op:
    backend: extract_long_text_op
    params:
      save_answer: true

external_mcp:
  tongyi_search:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/WebSearch/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"
  tongyi_web_parser:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/WebParser/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"
  bochaai_search:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/bochaai_search/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"
