[project]
name = "pycoro"
version = "1.1.4"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Tomperez98", email = "tomasperezalvarez@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
]

[project.urls]
Documentation = "https://github.com/Tomperez98/pycoro#readme"
Issues = "https://github.com/Tomperez98/pycoro/issues"
Source = "https://github.com/Tomperez98/pycoro"

[build-system]
requires = ["uv_build>=0.8.6,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.0",
    "poethepoet>=0.37.0",
    "basedpyright>=1.32.0",
]

[tool.poe.tasks]
fmt = "ruff format"
check = "ruff check"
type-check = "basedpyright"
test = "pytest"

[tool.basedpyright]
reportExplicitAny = false
reportAny = false
