[project]
name = "prt-sim"
version = "0.1.8"
description = "Python Research Toolkit - Simulation"
readme = "README.md"
authors = [
    { name = "Gavin Strunk", email = "gavin.strunk@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.0",
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "prt-datasets>=0.1.1",
    "prt-nn>=0.1.1",
    "pycocotools>=2.0.10",
    "pygame>=2.6.1",
    "scikit-image>=0.25.2",
    "torchmetrics>=1.8.2",
    "torchvision>=0.23.0",
    "ultralytics>=8.3.207",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "myst-parser>=4.0.1",
    "nbsphinx>=0.9.7",
    "pytest>=8.3.5",
    "sphinx>=8.1.3",
    "sphinx-book-theme>=1.1.4",
]

# --- JHU plugin entry points ---
[project.entry-points."jhu.envs"]
"prt-sim/Blackjack-v0" = "prt_sim.jhu.blackjack:Blackjack"
"prt-sim/GoldExplorer-v0" = "prt_sim.jhu.gold_explorer:GoldExplorer"
"prt-sim/KArmBandits-v0" = "prt_sim.jhu.bandits:KArmBandits"
"prt-sim/RobotGame-v0" = "prt_sim.jhu.robot_game:RobotGame"
