[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "core-universal4"
version = "4.50.3"
description = "Applitools Eyes Core SDK Server"
readme = "README.rst"
license = {file = "LICENSE"}
authors = [
    {name = "Applitools Team", email = "team@applitools.com"}
]
classifiers = [
    "Programming Language :: Python",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing",
]
requires-python = ">=3.7, <4"
dependencies = [
    "importlib-resources; python_version < '3.9'"
]

[project.urls]
Homepage = "https://applitools.com"

[tool.setuptools.packages.find]
where = ["."]
include = ["applitools*"]

[tool.setuptools.package-data]
"applitools.core_universal" = ["bin/*"]

[tool.setuptools]
zip-safe = false
