[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "files_com_mcp"
version = "1.0.39"
description = "MCP for the Files.com API"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = [
  "fastmcp==2.12.4",
  "files-com"
]

[project.scripts]
files-com-mcp = "files_com_mcp.__main__:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = ["tests", "tests.*", "doc"]

[tool.setuptools.package-data]
files_sdk = ["../_VERSION", "../README.md"]

[tool.black]
line-length=79
include="files_com_mcp/"
[tool.pyright]
include=["files_com_mcp"]
reportMissingTypeArgument=true
reportUnnecessaryCast=true
reportUnnecessaryComparison=true
reportUnnecessaryContains=true
reportUnnecessaryIsInstance=true
# The project currently uses dynamic types
reportGeneralTypeIssues=false