[tool.poetry]
name = "pyeasyphd"
version = "0.3.12"
description = "pyeasyphd"
license = "GPL-3.0-or-later"
authors = ["NextAI <nextartifintell@gmail.com>"]
maintainers = ["NextAI <nextartifintell@gmail.com>"]
readme = ["README.md"]
homepage = "https://github.com/Easy-PhD/pyeasyphd"
repository = "https://github.com/Easy-PhD/pyeasyphd"
documentation = "https://github.com/Easy-PhD/pyeasyphd"
keywords = ["Python", "Markdown", "LaTex"]
classifiers = ["Topic :: Software Development :: Libraries :: Python Modules"]

[tool.poetry.dependencies]
python = ">=3.12"
pyadvtools = "^0.2.4"
pybibtexer = "^0.2.3"

[tool.poetry.group.dev.dependencies]
mypy = "^1.18.1"
ruff = "^0.13.1"
pycodestyle = "^2.14.0"
pydocstyle = "^6.3.0"
flake8 = "^7.3.0"
isort = "^6.0.1"
black = "^25.1.0"
pyright = "^1.1.405"
sphinx = "^8.2.3"
sphinx-rtd-theme = "^3.0.2"
sphinx-copybutton = "^0.5.2"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 120
indent-width = 4

exclude = [".venv"]
extend-exclude = ["tests"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
ignore_missing_imports = true

[tool.black]
line-length = 120
skip-magic-trailing-comma = true

[tool.isort]
line_length = 120
profile = "black"
include_trailing_comma = true

[tool.pytest]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
