_target_: gfmrag.kg_construction.entity_linking_model.DPRELModel
model_name: Alibaba-NLP/gte-Qwen2-7B-instruct
root: tmp
use_cache: True
normalize: True
query_instruct: "Instruct: Given a entity, retrieve entities that are semantically equivalent to the given entity\nQuery: "
passage_instruct: null
model_kwargs: null
