[project]
name = "archiver_client"
version = "1.0.0b1"
description = "Pscheduler Result Archiver Client API"
readme = "README.md"
authors = [{ name = "Komal Thareja", email = "kthare10@renci.org" }]
license = { text = "Apache-2.0" }
requires-python = ">=3.8"

dependencies = ["requests"]

[build-system]
requires = ["flint"]
build-backend = "flint.buildapi"

[tool.flint]
package = "archiver_client"

