[project]
name = "lakeshore-tempcontrol"
version = "0.16.13"
description = "Lakeshore Temperature Control for CGSE"
authors = [
    {name = "IVS KU Leuven"}
]
maintainers = [
    {name = "Rik Huygen", email = "rik.huygen@kuleuven.be"},
    {name = "Sara Regibo", email = "sara.regibo@kuleuven.be"}
]
readme = {"file" = "README.md", "content-type" = "text/markdown"}
requires-python = ">=3.10"
license = "MIT"
keywords = [
    "CGSE",
    "Common-EGSE",
    "hardware testing",
    "software framework",
    "temperature control",
]
dependencies = [
    "cgse-common",
    "cgse-core",
    "cgse-tools",
    "cgse-gui",
    "PyQt5>=5.15.11",
]

[project.optional-dependencies]
test = ["pytest", "pytest-mock", "pytest-cov"]

[project.scripts]
lakeshore336_cs = 'egse.tempcontrol.lakeshore.lakeshore336_cs:cli'

[project.gui-scripts]
lakeshore336_ui = "egse.tempcontrol.lakeshore.lakeshore336_ui:main"

[project.entry-points."cgse.version"]
lakeshore-tempcontrol = 'egse.version:get_version_installed'

[project.entry-points."cgse.settings"]
lakeshore-tempcontrol = "lakeshore_tempcontrol:settings.yaml"

[project.entry-points."cgse.service.device_command"]
lakeshore336 = 'lakeshore_tempcontrol.cgse_services:lakeshore336'

[project.entry-points."cgse.explore"]
explore = "lakeshore_tempcontrol.cgse_explore"

[tool.hatch.build.targets.sdist]
exclude = [
    "/tests",
    "/pytest.ini",
    "/.gitignore",
]

[tool.hatch.build.targets.wheel]
packages = ["src/egse", "src/lakeshore_tempcontrol"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["E501"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
