[project]
name = "fashion-mnist-classifier"
version = "0.1.8"
authors = [
  { name="Ainhoa Del Rey", email="delrey.132148@e.unavarra.es"},
  { name="IÃ±igo Goikoetxea", email="goicoechea.128710@e.unavarra.es" },
  { name="Maria Ines", email="haddad.179806@e.unavarra.es" }
]

description = "An image classification model for Fashion MNIST using PyTorch Lightning."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
keywords = ["pytorch", "lightning", "fashion-mnist", "image-classification"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "numpy>=2.3.3",
    "pytorch-lightning>=2.5.5",
    "gradio>=4.0.0",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "scipy>=1.16.2"
]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
"Homepage" = "https://github.com/tu_usuario/fashion-mnist-classifier"
"Bug Tracker" = "https://github.com/tu_usuario/fashion-mnist-classifier/issues"

[project.scripts]
fashion-mnist-classifier = "my_project.train:main"
fashion-mnist-app = "my_project.app:main"

[dependency-groups]
dev = [
    "pdoc>=15.0.4",
    "black>=25.9.0",
    "flake8>=7.3.0",
    "build>=1.3.0",
    "twine>=6.2.0",
]
