[project]
name = "quda"
version = "2.0.37"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lark>=1.2.2",
    "rich>=14.0.0",
    "varname>=0.14.0",
    "typer>=0.16.0",
    "ygo>=1.2.6",
    "logair>=1.0.6",
    "lidb>=1.0.9",
    "xcals>=0.0.4",
    "toml>=0.10.2",
    "polars",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["quda", "quda.*"]

[project.scripts]
quda = "quda.cli:app"
