[package]
name = "mysql-type-plugin"
version = "0.1.26"
edition = "2021"
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mysql_type_plugin"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
sql-type = "0.29.0"
ariadne = "0.5"
ouroboros = "0.18"
