[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "pulumi-django-azure"
version = "1.0.47"
description = "Simply deployment of Django on Azure with Pulumi"
readme = "README.md"
authors = [{ name = "Maarten Ureel", email = "maarten@youreal.eu" }]
license = "MIT"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["django", "pulumi", "azure"]
dependencies = [
    "azure-identity (>=1.25.1,<2.0.0)",
    "azure-keyvault-secrets (>=4.10.0,<5.0.0)",
    "azure-mgmt-cdn (>=13.1.1,<14.0.0)",
    "azure-mgmt-resource (>=24.0.0,<25.0.0)",
    "collectfasta (>=3.3.1,<4.0.0)",
    "django (>=5.2.7,<6.0.0)",
    "django-azure-communication-email (>=1.4.0,<2.0.0)",
    "django-environ (>=0.12.0,<0.13.0)",
    "django-redis (>=6.0.0,<7.0.0)",
    "django-storages[azure] (>=1.14.6,<2.0.0)",
    "django-tasks[rq] (>=0.8.0,<0.10.0)",
    "psycopg-binary (>=3.2.11,<4.0.0) ; sys_platform == \"win32\"",
    "psycopg[c] (>=3.2.11,<4.0.0) ; sys_platform == \"linux\"",
    "pulumi (>=3.203.0)",
    "pulumi-azure (>=6.28.0,<7.0.0)",
    "pulumi-azure-native (>=3.8.0)",
    "pulumi-random (>=4.18.4)",
    "redis[hiredis] (>=6.4.0,<7.0.0)",
    "tenacity (>=9.1.2,<10.0.0)"
]
requires-python = ">=3.11,<3.14"

[project.urls]
Homepage = "https://gitlab.com/MaartenUreel/pulumi-django-azure"


[tool.poetry.group.dev.dependencies]
build = "^1.3.0"
mkdocs-material = "^9.6.22"
pre-commit = "^4.3.0"
ruff = "^0.14.1"
twine = "^6.2.0"

[tool.ruff]
line-length = 140

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
