[project]
name = "debby-cli"
version = "0.2.1"
description = "A dbt project linter"
authors = [{ name = "Tom Waterman" }]
readme = "README.pypi.md"
requires-python = ">=3.10,<4.0"

[project.scripts]
debby = "debby.cli:cli"

[tool.poetry]
packages = [{ include = "debby" }]

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[tool.poetry.group.test.dependencies]
pytest = "^8.4.2"
pytest-django = "^4.11.1"
dbt-core = "^1.10.13"
dbt-duckdb = "^1.9.6"
jinja2 = "^3.1.6"
py-markdown-table = "^1.3.0"
black = "^25.9.0"
ruamel-yaml = "^0.18.15"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.5.39"

[tool.poetry.group.web.dependencies]
django = "^5.2.7"
psycopg2-binary = "^2.9.11"
gunicorn = "^23.0.0"
djangorestframework = "^3.16.1"
djangorestframework-stubs = "^3.16.4"


[tool.poetry.group.dev.dependencies]
pyyaml = "^6.0.3"

[tool.poetry.dependencies]
python-dotenv = "^1.1.1"
click = "^8.3.0"
rich = "^14.2.0"
tomlkit = "^0.13.3"
packaging = "^25.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
addopts = "--reuse-db"
testpaths = ["tests"]
pythonpath = ["web", "web/apps"]
