[project]
name = "dnnets"
version = "0.2.1"
description = "Running multilayer perceptrons on the CPU"
authors = [{name = "Hannes Braun", email = "hannes@hannesbraun.net"}]
requires-python = ">= 3.10"
readme = "README.md"
license = "LGPL-3.0-only"
license-files = ["LICENSE"]
keywords = ["Neural Network", "Feedforward", "Multilayer perceptron"]
classifiers = [
	"Development Status :: 4 - Beta",
	# not there yet: "Development Status :: 5 - Production/Stable",
	"Intended Audience :: Developers",
	"Programming Language :: Other",
	"Programming Language :: Python",
	"Topic :: Scientific/Engineering :: Artificial Intelligence",
	"Topic :: Software Development"
]

[project.optional-dependencies]
numpy = ["numpy>=2.0.0"]

[project.urls]
Homepage = "https://git.sr.ht/~hannes/dnnets"
Documentation = "https://hannesbraun.net/share/doc/dnnets/python/index.html"
Repository = "https://git.sr.ht/~hannes/dnnets"
Changelog = "https://git.sr.ht/~hannes/dnnets/refs"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = ["*.dll", "*.dylib", "*.so"]

[tool.hatch.build.targets.wheel]
artifacts = ["*.dll", "*.dylib", "*.so"]
packages = ["python/dnnets"]

[tool.hatch.build.targets.wheel.hooks.custom]

