[project]
name = "laissez"
version = "0.0.1a6"
description = "Agents spending you can trust"
readme = "README.md"
authors = [
    { name = "Matthew Collins", email = "matthew@laissez.xyz" }
]
requires-python = ">=3.10"
dependencies = [
    "eth-account>=0.13.7",
    "fastmcp>=2.12.4",
    "httpx>=0.28.1",
    "x402>=0.2.1",
]

[project.scripts]
laissez = "laissez:main"

[project.optional-dependencies]
examples = [
    "dedalus-labs==0.1.0a9",
    "fastmcp>=2.12.4",
    "openai>=2.3.0",
    "pydantic-ai>=1.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
examples = [
    "dedalus-labs==0.1.0a9",
    "fastmcp>=2.12.4",
    "openai>=2.3.0",
    "pydantic-ai>=1.1.0",
]
