[project]
name = "baidu-mcp-server"
version = "0.1.7"
description = "MCP Server for searching via Baidu"
readme = "README.md"
authors = [{ name = "Evilran" }]
requires-python = ">=3.10"
dependencies = ["beautifulsoup4>=4.13.3", "httpx>=0.28.1", "mcp[cli]>=1.3.0", "readabilipy>=0.3.0", "markdownify>=1.1.0", "playwright"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/Evilran/baidu-mcp-server"
Issues = "https://github.com/Evilran/baidu-mcp-server/issues"

[project.scripts]
baidu-mcp-server = "baidu_mcp_server.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
