_target_: gfmrag.kg_construction.entity_linking_model.DPRELModel
model_name: Alibaba-NLP/gte-large-en-v1.5
root: tmp
use_cache: True
normalize: True
query_instruct: null
passage_instruct: null
model_kwargs: null
