[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "knowrithm-py"
version = "0.1.17"
authors = [
    {name = "Steven Saad", email = "stevensaad35@gmail.com"},
]
description = "Knowrithm Python SDK"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    # Add your dependencies here
    "requests>=2.25.0"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["knowrithm_py*"]

[project.urls]
Homepage = "https://github.com/Knowrithm/knowrithm-py.git"