[project]
name = "thinagents"
description = "A lightweight AI Agent framework"
authors = [{ name = "Prabhu Kiran Konda" }]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
keywords = ["AI", "LLM", "Agentic AI", "AI Agents"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["litellm>=1.70.0", "graphviz>=0.20.0"]
dynamic = ["version"]

[project.optional-dependencies]
web = ["fastapi>=0.104.0", "uvicorn>=0.24.0"]

[project.urls]
Homepage = "https://github.com/PrabhuKiran8790/thinagents"

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = { find = { exclude = [
    "tests",
    "tests.*",
    "examples",
    "examples.*",
    "thinagents.frontend",
    "thinagents.frontend.*",
] } }

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
