[package]
name = "llmcc-bindings"
version.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "llmcc_bindings"
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
llmcc-core.workspace = true
llmcc-rust.workspace = true
llmcc-python.workspace = true
pyo3.workspace = true
serde.workspace = true
serde_json.workspace = true
