[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mariner-stats"
version = "0.1.8"
description = "MARINER: marginal selection + UniLasso with interactions."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [{name = "Aymen Echarghaoui"}]
keywords = ["lasso", "feature-selection", "interactions", "regression", "scikit-learn"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
]

dependencies = [
  "hiutils-aymen>=0.1.8",
]

[tool.setuptools.packages.find]
where = ["src"]
