[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "musan"
version = "0.0.2"
readme = "README.md"
description = "This is the module for work with mel-specs based music analitycs models"
authors = [
    {name = "nikarpoff", email = "nik.karpov103@mail.ru"}
]
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
keywords = ["transformers", "music", "analitycs", "hugging_face"]
dependencies = [
    'torch==2.7.0',
    'torchvision==0.22.0',
    'torchaudio==2.7.0',
    'huggingface_hub>=0.35.0'
]

[project.urls]
Repository = "https://github.com/nikarpoff"
"Bug Tracker" = "https://github.com/yourusername/your-repo/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"