[tool.poetry]
name = "future_sales_inno_ds_project"
version = "0.0.16"
description = "DS project"
authors = ["Katsiaryna <katsiaryna.shymchonak@innowise.com>"]
readme = "README.md"
packages = [
  { include = "future_sales_inno_ds_project", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"

# Core ML stack
numpy = "~1.26.0"
pandas = "~2.1.1"
scikit-learn = "~1.3.2"
optuna = "~4.5.0"
hyperopt = "~0.2.7"
lightgbm = "~4.6.0"
xgboost = "~2.0.3"
shap = "~0.48.0"
dill = "~0.3.8"

# TensorFlow and Keras
tensorflow = "~2.14.0"
keras = "~2.14.0"
typing-extensions = ">=4.11,<5"
protobuf = "~4.23.4"

# Utils
python-dotenv = "~0.21.1"
requests = "~2.32.4"
matplotlib = ">=3.8.0"
setuptools = "<81"

# Integrations
openai = "~2.2.0"
neptune = "~1.14.0"
PyGithub = "~2.4.0"


[tool.poetry.plugins."poetry.dynamic-versioning"]
"poetry-dynamic-versioning" = "poetry_dynamic_versioning.plugin"

[tool.dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
