[project]
name = "asteroid_spinprops"
version = "0.2.27"
description = "Collection of tools used for fitting sHG1G2 and ssHG1G2 photometric models to sparse asteroid photometry"
authors = [
    {name = "Odysseas",email = "odysseas.xenos@proton.me"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "astropy (==7.0.0)",
    "fink-utils (==0.43.0)",
    "matplotlib (==3.10.1)",
    "nifty-ls (==1.1.0)",
    "pandas (==2.3.3)",
    "scipy (==1.16.2)",
    "tqdm (==4.67.1)",
    "space-rocks (==1.9.14)"
]

[tool.poetry]
packages = [
    {include = "asteroid_spinprops"},
]

[project.urls]
homepage = "https://gitlab.com/odysseas_xenos/asteroid-spinprops"
repository = "https://gitlab.com/odysseas_xenos/asteroid-spinprops"
	

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
