[project]
name = "rpa-toolkit"
version = "0.1.1"
description = "A Python toolkit for Robotic Process Automation (RPA) with enhanced processing and solutions to common automation challenges."
readme = "README.md"
authors = [
    { name = "fnxL", email = "48607132+fnxL@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastexcel>=0.16.0",
    "openpyxl>=3.1.5",
    "polars>=1.34.0",
    "pymupdf>=1.26.5",
    "xlsx2csv>=0.8.4",
    "xlsxwriter>=3.2.9",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]


[project.urls]
Homepage = "https://github.com/fnxL/rpa-toolkit"
Issues = "https://github.com/fnxL/rpa-toolkit/issues"


[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.3.0",
]
