[build-system]
build-backend = "hatchling.build"

requires = ["hatchling"]

[project]
name = "dspawpy"
description = "Tools for dspaw"
readme = "README.md"
keywords = [
  "atom",
  "band-structure",
  "density-of-states",
  "dft",
  "ds-paw",
  "hzw",
  "pymatgen",
  "quantum chemistry",
  "structure",
]

license = { file = "LICENSE.txt" }
maintainers = [{ name = "zzl", email = "ZhengZhilin@hzwtech.com" }]
authors = [
  { name = "zzl", email = "ZhengZhilin@hzwtech.com" },
  { name = "txwang" },
  { name = "ymxia" },
  { name = "syyl" },
  { name = "hql" },
]
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dynamic = ["version"]
dependencies = [
  "build",
  "h5glance",       # show structure of hdf5 file
  "h5py",           # parse h5
  "hatchling",
  "loguru",         # log
  "polars>=0.18",   # speed up pandas, write_csv starts from 0.18
  "prompt-toolkit", # cli completer
  "pymatgen",
  "statsmodels",
  "tables",         # h5 dump
  "numpy<2",        # avoid numpy error in pmg
  "ase",            # write png/gif
]
optional-dependencies.dev = [
  "better-exceptions", # diagnose
  "pre-commit",
  "pytest",
  "pytest-cov",
  "pytest-html",
  "pytest-instafail",
  "syrupy",
  "ruff",
  "twine",
]
optional-dependencies.manual = [
  "jieba",                          # search in Chinese
  "sphinx",                         # this engine builds API
  "sphinx-autodoc-typehints",       # no more re-writing type annotation in docstring
  "sphinx-copybutton",              # show copy-button for sphinx proj
  "sphinx-design",                  # dropdown
  "sphinx-mathjax-offline",         # offline mathjax
  "sphinx-multiversion",            # show various versions of doc
  "sphinx-rtd-theme",
  "sphinxcontrib-bibtex",           # reference
  "sphinxcontrib-napoleon",         # parse docstring in numpy style for API
  "sphinxcontrib-svg2pdfconverter", # convert svg to pdf
]
urls.homepage = "http://cloud.hzwtech.com/"
scripts.dspawpy = "dspawpy.cli.entrypoint:main"

[tool.hatch.build.targets.sdist]
packages = ["src/dspawpy"]

[tool.hatch.version]

path = "src/dspawpy/__init__.py"

[tool.ruff]
target-version = "py39"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
dspawpy = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
manual = { features = ["manual"], solve-group = "default" }
[tool.pixi.dependencies]
ruff = ">=0.11.6,<0.12"
watchfiles = ">=1.0.5,<2"
syrupy = "*"

[tool.basedpyright]
typeCheckingMode = 'standard'

[dependency-groups]
docs = [
  "jieba>=0.42.1",
  "sphinx>=7.4.7",
  "sphinx-copybutton>=0.5.2",
  "sphinx-design>=0.6.1",
  "sphinx-mathjax-offline>=0.0.2",
  "sphinx-multiversion>=0.2.4",
  "sphinx-rtd-theme>=3.0.2",
  "sphinxcontrib-bibtex>=2.6.5",
  "sphinxcontrib-napoleon>=0.7",
  "sphinxcontrib-svg2pdfconverter>=1.3.0",
]
